# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --yes --force-yes update -qq; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --yes libudunits2-dev; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install udunits; fi;
